# Setup
title:        马马得儿
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "zh"

# About/contact
author:
  name:       li mao
  url:        http://rhastali.space 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown